name: volley_app
description: "A new Flutter project."

# Prevent accidental publication to pub.dev.
publish_to: 'none'

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0" # Ensure compatibility with the Dart SDK.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Provides iOS-style icons.
  http: ^0.13.6 # For making HTTP requests.
  image_picker: ^0.8.7+4 # For selecting images from gallery or camera.
  permission_handler: ^10.2.0 # For managing runtime permissions.
  stomp_dart_client: ^2.1.0 # For STOMP WebSocket communication.
  flutter_map: ^4.0.0 # For displaying OpenStreetMap tiles.
  latlong2: ^0.8.1 # Provides LatLng support for flutter_map.

dev_dependencies:
  flutter_test:
    sdk: flutter # For writing unit tests for Flutter apps.
  flutter_lints: ^5.0.0 # Recommended lint rules for Flutter.

flutter:
  uses-material-design: true # Ensures Material Icons are included.

  # Uncomment and add assets if needed:
  #  assets:
  #    - assets/default_profile.png # Include the default profile picture.

  # Uncomment and configure fonts if needed:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

